@startuml "ContactAppClassDiagram"

class Contact {
    String firstName
    String lastName
    String company
    String jobTitle
    PhoneNumber[] phoneNumbers
    EmailAddress[] emailAddresses

    void addPhoneNumber()
    void addEmailAddress()
    void mergeContact()
}

class PhoneNumber {
    String phoneNumber
    String label
}

class EmailAddress {
    String email
    String label
}

class User {
    Contact[] contacts

    void createContact()
    void updateContact()
    void deleteContact()
    void mergeContacts()
    void filterContacts()
    void listContacts()
}

Contact "1" -u- "0..*" PhoneNumber
Contact "1" -d- "0..*" EmailAddress
User "1" -d-> "0..*" Contact

@enduml